# Generated by Django 4.0.5 on 2022-06-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('velocidad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
