# Generated by Django 4.0.5 on 2022-07-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_personaje_delete_objetos'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('año', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreM', models.CharField(max_length=20)),
                ('edadM', models.IntegerField()),
            ],
        ),
    ]
