# Generated by Django 4.0.5 on 2022-07-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_auto_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='año',
            field=models.DateField(),
        ),
    ]
