# Generated by Django 4.0.5 on 2022-07-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_auto_año'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auto',
        ),
        migrations.DeleteModel(
            name='personaje',
        ),
    ]
