# Generated by Django 4.0.5 on 2022-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_auto_delete_personaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='owner',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
