# Generated by Django 4.0.5 on 2022-07-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_mascota_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='owner',
        ),
    ]
