# Generated by Django 4.0.5 on 2022-07-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_mascota_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='avatar',
        ),
    ]
