# Generated by Django 4.0.5 on 2022-07-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_publisher_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('creador', models.CharField(blank=True, max_length=20)),
                ('ingredientes', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
            ],
        ),
    ]
